name: Build & test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
      - uses: actions/checkout@v4
      - name: Setting up pnpm
        uses: pnpm/action-setup@v4
      - name: Setting up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint --if-present
      - run: pnpm run build --if-present
        env:
          CI: true
